icons_format = "{icon}"

[theme]
theme = "solarized-dark"
#theme = "plain"
# theme = "native"
[theme.overrides]
#idle_bg = "#123456"
idle_bg = "#222222"
#idle_fg = "#abcdef"
separator_bg = "#222222"

[icons]
icons = "awesome4"
[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "keyboard_layout"
driver = "setxkbmap"
interval = 15
[block.mappings]
"us,de,no,latam" = "us"


# [[block]]
# block = "keyboard_layout"
# driver = "xkbswitch"
# interval = 15

# [[block]]
# block = "keyboard_layout"
# driver = "localebus"

# [[block]]
# block = "keyboard_layout"
# driver = "kbddbus"
# [block.mappings]
# "English (US)" = "us"
# "Bulgarian (new phonetic)" = "bg"

# [[block]]
# block = "keyboard_layout"
# driver = "sway"
# sway_kb_identifier = "1133:49706:Gaming_Keyboard_G110"

# [[block]]
# block = "keyboard_layout"
# driver = "sway"
# format = " $layout "
#[block.mappings]
#"English (Workman)" = "EN"
#"Russian (N/A)" = "RU"


#[[block]]
#block = "cpu"
#icons_format = "{icon}"
#[block.theme_overrides]
#idle_bg = "#123456"
#idle_fg = "#abcdef"
#[block.icons_overrides]
#cpu_boost_on = "ON"
#cpu_boost_off = "OFF"

#[[block]]
#block = "disk_space"
#path = "/home"
#info_type = "available"
#alert_unit = "GB"
#interval = 20
#warning = 20.0
#alert = 10.0
#format = " $icon home: $available.eng(w:2) "


#[[block]]
#block = "disk_space"
#path = "/repo"
#info_type = "available"
#alert_unit = "GB"
#interval = 20
#warning = 20.0
#alert = 10.0
#format = " $icon repo: $available.eng(w:2) "


#[[block]]
#block = "memory"
#format = " $icon $mem_total_used_percents.eng(w:2) "
#format_alt = " $icon_swap $swap_used_percents.eng(w:2) "


[[block]]
block = "battery"
format = " $percentage {$time |}"
device = "DisplayDevice"
driver = "upower"


[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "sound"
driver = "pulseaudio"
device_kind = "source"
format = " $icon { $volume|} {$active_port |}"
[block.active_port_mappings]
"analog-input-rear-mic" = "" # Mapping to an empty string makes `$active_port` absent
"analog-input-front-mic" = "ERR!"

[[block]]
block = "time"
interval = 5
#format = " $timestamp.datetime(f:'%a %d/%m %R') "
format = " $timestamp.datetime(f:'%a %Y-%m-%d %R') "
